import Link from "next/link";
import PrintPageButton from "@/components/PrintPageButton";
import { createSupabaseAdminClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

type Row = Record<string, unknown>;
function clean(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function noteValue(notes: string, label: string) { const line = notes.split("\n").find((entry) => entry.toLowerCase().startsWith(`${label.toLowerCase()}:`)); return line ? line.slice(line.indexOf(":") + 1).trim() : ""; }
function shipTo(order: Row) { return [clean(order.ship_to_name) || clean(order.customer_name), clean(order.ship_to_address || order.project_address_line1), clean(order.ship_to_address2 || order.project_address_line2), `${clean(order.ship_to_city || order.project_city)}, ${clean(order.ship_to_state || order.project_state)} ${clean(order.ship_to_zip || order.project_postal_code)}`.trim()].filter(Boolean).join("\n"); }
async function loadOrder(orderId: string) { const supabase = createSupabaseAdminClient(); const { data, error } = await supabase.from("orders").select("*").eq("id", orderId).maybeSingle(); if (error) throw new Error(error.message); return data as Row | null; }

export default async function CustomerWarrantyPage({ params }: { params: Promise<{ orderId: string }> }) {
  const { orderId } = await params;
  const order = await loadOrder(orderId);
  if (!order) return <main className="min-h-screen bg-neutral-50 px-6 py-10"><section className="mx-auto max-w-3xl rounded-2xl bg-white p-6"><h1 className="text-2xl font-black">Warranty paperwork unavailable</h1></section></main>;
  const notes = clean(order.manufacturer_notes || order.notes);
  const customerName = clean(order.warranty_customer_name) || noteValue(notes, "Name") || clean(order.customer_name) || "Not provided";
  const customerEmail = clean(order.warranty_customer_email) || noteValue(notes, "Email") || clean(order.customer_email) || "Not provided";
  const customerPhone = clean(order.warranty_customer_phone) || noteValue(notes, "Phone") || clean(order.customer_phone) || "Not provided";
  return <main className="min-h-screen bg-neutral-50 px-6 py-10 text-neutral-950 print:bg-white print:px-0 print:py-0"><section className="mx-auto max-w-5xl rounded-2xl bg-white p-8 shadow-sm ring-1 ring-neutral-200 print:rounded-none print:shadow-none print:ring-0"><div className="print:hidden"><Link href="/" className="text-sm font-semibold text-green-800">Cattle Guard Forms</Link></div><p className="mt-6 text-sm font-bold uppercase tracking-wide text-green-800 print:mt-0">Cattle Guard Forms</p><h1 className="mt-2 text-3xl font-black">CowStop Warranty Paperwork</h1><p className="mt-3 text-sm leading-6 text-neutral-700">Order-specific customer warranty and support record.</p><div className="mt-6 print:hidden"><PrintPageButton /></div><section className="mt-8 grid gap-5 md:grid-cols-2"><div className="rounded-xl border border-neutral-200 bg-neutral-50 p-5"><h2 className="text-xl font-black text-green-950">Customer Warranty Information</h2><p className="mt-3 text-sm"><span className="font-bold">Customer name:</span> {customerName}</p><p className="mt-2 text-sm"><span className="font-bold">Customer phone:</span> {customerPhone}</p><p className="mt-2 text-sm"><span className="font-bold">Customer email:</span> {customerEmail}</p></div><div className="rounded-xl border border-neutral-200 bg-neutral-50 p-5"><h2 className="text-xl font-black text-green-950">Order Information</h2><p className="mt-3 text-sm"><span className="font-bold">Order:</span> {clean(order.id).slice(0, 8)}</p><p className="mt-2 text-sm"><span className="font-bold">Product:</span> {clean(order.product_name) || "CowStop Reusable Form"}</p><p className="mt-2 text-sm"><span className="font-bold">Quantity:</span> {Number(order.cowstop_quantity ?? order.quantity ?? 0)}</p><p className="mt-2 whitespace-pre-line text-sm"><span className="font-bold">Ship-to:</span> {shipTo(order)}</p></div></section><section className="mt-8 rounded-xl border border-green-200 bg-green-50 p-5 print:border-neutral-400 print:bg-white"><h2 className="text-xl font-bold text-green-950">CowStop material and construction</h2><p className="mt-3 text-sm leading-6 text-green-950">CowStop forms are manufactured from high-density polyethylene. Keep this page with the order record.</p></section><section className="mt-8 rounded-xl border border-amber-200 bg-amber-50 p-5 print:border-neutral-400 print:bg-white"><h2 className="text-xl font-bold text-amber-950">Warranty review notes</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-amber-950"><li>Warranty review is limited to manufacturer defects.</li><li>Photo documentation may be required.</li><li>Keep delivery records, BOL, and this paperwork with the order file.</li></ul></section></section></main>;
}
